const ROLES = {
  CUSTOMER: 'CUSTOMER',
  VENDOR: 'VENDOR',
  ADMIN: 'ADMIN',
};

const VENDOR_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
};

const ORDER_STATUS = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  CONFIRMED: 'CONFIRMED',    // payment done — awaiting vendor acceptance
  ACCEPTED: 'ACCEPTED',      // vendor explicitly accepted the order
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

const DELIVERY_STATUS = {
  NOT_INITIATED: 'NOT_INITIATED',
  PICKUP_SCHEDULED: 'PICKUP_SCHEDULED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
};

// Vendor-updatable order statuses (used by PATCH /:id/status)
// Accept and reject have their own dedicated endpoints
const VENDOR_ALLOWED_STATUS_TRANSITIONS = {
  [ORDER_STATUS.ACCEPTED]:        [ORDER_STATUS.PREPARING],
  [ORDER_STATUS.PREPARING]:       [ORDER_STATUS.READY_FOR_PICKUP],
  [ORDER_STATUS.READY_FOR_PICKUP]: [ORDER_STATUS.OUT_FOR_DELIVERY],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED],
};

// Statuses from which a vendor can reject an order
const VENDOR_REJECTABLE_STATUSES = [ORDER_STATUS.CONFIRMED, ORDER_STATUS.ACCEPTED];

module.exports = {
  ROLES,
  VENDOR_STATUS,
  ORDER_STATUS,
  PAYMENT_STATUS,
  DELIVERY_STATUS,
  VENDOR_ALLOWED_STATUS_TRANSITIONS,
  VENDOR_REJECTABLE_STATUSES,
};
